#+TITLE: iwatch

* NAME

#+begin_src
iwatch
#+end_src

* SYNOPSIS

#+begin_src
iwatch FILES CMD
#+end_src

* DESCRIPTION

Run =CMD= every time one of =FILE(s)= is written to.

=FILE(s)=: A comma, space, or newline separated list of files *or* a
=FILESPEC=.  See FILESPEC below.

=CMD=: Command to run when an event happens.  Inside =CMD=, occurrences of
=%^= are expanded to the whole list of files and =%=:

#+begin_src sh
iwatch my_script.py 'python3 %'
#+end_src

If =CMD= is long running the previous run of =CMD= is sent the =TERM=
signal and a new run is started when an event happens.

* FILESPEC

If the =FILE= argument starts with =@<path>=, then =iwatch= will watch all files
tracked by git =<path>= relative to PWD (even if <path> starts with a '/')
and for =@:<path>=

* CAVEATS

=CMD= is run whenever certain events happen to the watched files so not
exactly when the file is written to.  Other events are ignored like
opening the file which happens very frequently if we have an LSP
running.

* BUGS AND CONTRIBUTIONS

Please submit an issue on [[https://github.com/philippecarphin/iwatch]] or
submit a merge request with any improvements.

* LORE

Even though I started this using =fswatch= on MacOS, I thought MacOS had
inodes which is why I called it =iwatch=.  This was a long time ago :).

* AUTHOR

Philippe Carphin
